@startuml minesfield
class Level {
    string Name
    int    X
    int    Y
    int    amountMines
}
class Board {
    int[][]         dimention
    JButton [][]    pieces
}
class Piece {
    int[][] position
    bool    isMine
}
class Mine
{
    void blow()
}


Level - Board : have 1 >
Board o- Piece
Piece ^- Mine
@enduml